; Script generated by the HM NIS Edit Script Wizard.                                                          

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "QtLobby"     
!define PRODUCT_VERSION "1.0prealpha"
!define PRODUCT_PUBLISHER "QtLobby Development Team"
!define PRODUCT_WEB_SITE "http://code.google.com/p/qtlobby/"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\qtlobby.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"                                                          

SetCompressor /SOLID lzma

; MUI 1.67 compatible ------
!include "MUI.nsh"          

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page               
!insertmacro MUI_PAGE_LICENSE "LICENSE.rtf"
; Directory page                           
!insertmacro MUI_PAGE_DIRECTORY            
; Instfiles page                           
!insertmacro MUI_PAGE_INSTFILES            
; Finish page                              
!define MUI_FINISHPAGE_RUN "$INSTDIR\qtlobby.exe"
!insertmacro MUI_PAGE_FINISH                     

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; Reserve files
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "qtlobby_installer.exe"          
InstallDir "$PROGRAMFILES\QtLobby"       
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show                            
ShowUnInstDetails show                          

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"    
  SetOverwrite try         
  File "..\build\msvcp90.dll"
  File "..\build\msvcr90.dll"
  File "..\build\libgcc_s_dw2-1.dll"
  File "..\build\exchndl.dll"
  File "..\build\qscintilla2.dll"   
  File "..\build\QtCore4.dll"       
  File "..\build\QtGui4.dll"        
  File "..\build\QtNetwork4.dll"    
  File "..\build\QtOpenGL4.dll"     
  File "..\build\QtScript4.dll"     
  File "..\build\QtScriptTools4.dll"
  File "..\build\QtXml4.dll"        
  File "..\build\Microsoft_VC90_CRT_x86.msi"
  File "..\build\policy_9_0_Microsoft_VC90_CRT_x86.msi"
                                                       
  SetOverwrite ifnewer                                 
  File "release\qtlobby.exe"                           
  CreateDirectory "$SMPROGRAMS\QtLobby"                
  CreateShortCut "$SMPROGRAMS\QtLobby\QtLobby.lnk" "$INSTDIR\qtlobby.exe"
  CreateShortCut "$DESKTOP\QtLobby.lnk" "$INSTDIR\qtlobby.exe"           
SectionEnd                                                               

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\QtLobby\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"          
  CreateShortCut "$SMPROGRAMS\QtLobby\Uninstall.lnk" "$INSTDIR\uninst.exe"                 
SectionEnd                                                                                 

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\qtlobby.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\qtlobby.exe"   
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"  
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"   
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"     
                                                                                                        
  DetailPrint "Installing CRT assembly..."                                                              
  ExecWait 'msiexec /i "$INSTDIR\Microsoft_VC90_CRT_x86.msi" /qn'                                       
  ExecWait 'msiexec /i "$INSTDIR\policy_9_0_Microsoft_VC90_CRT_x86.msi" /qn'                            
  Delete "$INSTDIR\Microsoft_VC90_CRT_x86.msi"                                                          
  Delete "$INSTDIR\policy_9_0_Microsoft_VC90_CRT_x86.msi"                                               
SectionEnd                                                                                              


Function un.onUninstSuccess
  HideWindow               
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd                                                                                  

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort                                                                                                                                      
FunctionEnd                                                                                                                                  

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"         
  Delete "$INSTDIR\qtlobby.exe"        
  Delete "$INSTDIR\QtXml4.dll"         
  Delete "$INSTDIR\QtScriptTools4.dll"
  Delete "$INSTDIR\QtScript4.dll"
  Delete "$INSTDIR\QtOpenGL4.dll"
  Delete "$INSTDIR\QtNetwork4.dll"
  Delete "$INSTDIR\QtGui4.dll"
  Delete "$INSTDIR\QtCore4.dll"
  Delete "$INSTDIR\qscintilla2.dll"
  Delete "$INSTDIR\libgcc_s_dw2-1.dll"
  Delete "$INSTDIR\msvcr90.dll"
  Delete "$INSTDIR\msvcp90.dll"

  Delete "$SMPROGRAMS\QtLobby\Uninstall.lnk"
  Delete "$SMPROGRAMS\QtLobby\Website.lnk"
  Delete "$DESKTOP\QtLobby.lnk"
  Delete "$SMPROGRAMS\QtLobby\QtLobby.lnk"

  RMDir "$SMPROGRAMS\QtLobby"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd
